from setuptools import setup, find_packages

setup(
  name = 'general_motion_retargeting',
  packages = find_packages(),
  author="Yanjie Ze",
  author_email="lastyanjieze@gmail.com",
  description="General Motion Retargeting (GMR) for Humanoid Robots",
  long_description=open("README.md").read(),
  long_description_content_type="text/markdown",
  url="https://github.com/YanjieZe/GMR",
  license="MIT",
  version="0.2.0",
  install_requires=[
    "loop_rate_limiters",
    "mink",
    "mujoco",
    "numpy==1.26.0",
    "scipy",
    "qpsolvers[proxqp]",
    "rich",
    "tqdm",
    "opencv-python==4.8.1.78",
    "natsort",
    "psutil",
    "smplx @ git+https://github.com/vchoutas/smplx",
    "protobuf",
    "redis[hiredis]",
    "imageio[ffmpeg]",
  ],
  python_requires='>=3.10',
)
